# Generated by Django 2.2.5 on 2019-11-04 09:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_analysis.Analysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InputDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('required', models.BooleanField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_analysis.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='FloatInputDefinition',
            fields=[
                ('inputdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.InputDefinition')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('default', models.FloatField(blank=True, null=True)),
            ],
            bases=('django_analysis.inputdefinition',),
        ),
        migrations.CreateModel(
            name='IntegerInputDefinition',
            fields=[
                ('inputdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.InputDefinition')),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('default', models.IntegerField(blank=True, null=True)),
            ],
            bases=('django_analysis.inputdefinition',),
        ),
        migrations.CreateModel(
            name='NumberInput',
            fields=[
                ('input_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.Input')),
            ],
            bases=('django_analysis.input',),
        ),
        migrations.CreateModel(
            name='StringInputDefinition',
            fields=[
                ('inputdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.InputDefinition')),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('default', models.CharField(blank=True, max_length=500, null=True)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
            ],
            bases=('django_analysis.inputdefinition',),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('analysis_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_analysis.AnalysisVersion')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_analysis.Analysis')),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_analysis.Run'),
        ),
        migrations.AddField(
            model_name='analysisversion',
            name='input_specification_set',
            field=models.ManyToManyField(to='django_analysis.InputSpecification'),
        ),
        migrations.CreateModel(
            name='StringInput',
            fields=[
                ('input_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.Input')),
                ('value', models.CharField(max_length=1000)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_analysis.StringInputDefinition')),
            ],
            bases=('django_analysis.input',),
        ),
        migrations.CreateModel(
            name='IntegerInput',
            fields=[
                ('numberinput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.NumberInput')),
                ('value', models.IntegerField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_analysis.IntegerInputDefinition')),
            ],
            bases=('django_analysis.numberinput',),
        ),
        migrations.CreateModel(
            name='FloatInput',
            fields=[
                ('numberinput_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.NumberInput')),
                ('value', models.FloatField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_analysis.FloatInputDefinition')),
            ],
            bases=('django_analysis.numberinput',),
        ),
    ]
