# Generated by Django 2.2.5 on 2019-11-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdefinition',
            name='analysis',
        ),
        migrations.AddField(
            model_name='inputdefinition',
            name='input_specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_analysis.InputSpecification'),
        ),
        migrations.AlterField(
            model_name='analysisversion',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_analysis.Analysis'),
        ),
    ]
