# Generated by Django 3.0.6 on 2020-05-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinputdefinition',
            name='as_tuple',
            field=models.BooleanField(default=False),
        ),
    ]
