# Generated by Django 3.0.8 on 2020-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdefinition',
            name='value_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directoryinput',
            name='value',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=1000, verbose_name='/media/veracrypt1/media'),
        ),
        migrations.AlterField(
            model_name='fileoutput',
            name='value',
            field=models.FilePathField(blank=True, max_length=1000, null=True, verbose_name='/media/veracrypt1/media'),
        ),
    ]
