# Generated by Django 2.2.5 on 2019-11-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0002_auto_20191104_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdefinition',
            name='input_specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_analysis.InputSpecification'),
        ),
    ]
