# Generated by Django 3.0.8 on 2020-07-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0002_auto_20200712_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdefinition',
            name='value_method',
        ),
    ]
