# Generated by Django 2.2.5 on 2019-11-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0003_auto_20191104_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisversion',
            name='input_specification_set',
        ),
        migrations.AddField(
            model_name='analysisversion',
            name='input_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_analysis.InputSpecification'),
        ),
    ]
