# Generated by Django 3.0.7 on 2020-07-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0004_inputdefinition_db_value_preprocessing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryinput',
            name='value',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=1000, verbose_name='/media/groot/Data/media'),
        ),
        migrations.AlterField(
            model_name='fileoutput',
            name='value',
            field=models.FilePathField(blank=True, max_length=1000, null=True, verbose_name='/media/groot/Data/media'),
        ),
        migrations.AlterField(
            model_name='listinputdefinition',
            name='element_type',
            field=models.CharField(choices=[('BLN', 'Boolean'), ('INT', 'Integer'), ('FIL', 'File'), ('FLT', 'Float'), ('STR', 'String'), ('TUP', 'Tuple')], max_length=3),
        ),
        migrations.AlterField(
            model_name='listoutputdefinition',
            name='element_type',
            field=models.CharField(choices=[('BLN', 'Boolean'), ('INT', 'Integer'), ('FIL', 'File'), ('FLT', 'Float'), ('STR', 'String'), ('TUP', 'Tuple')], max_length=3),
        ),
    ]
