# Generated by Django 3.0.8 on 2020-09-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0004_inputdefinition_db_value_preprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='destination_run_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipe',
            name='source_run_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listinputdefinition',
            name='element_type',
            field=models.CharField(choices=[('BLN', 'Boolean'), ('INT', 'Integer'), ('FIL', 'File'), ('FLT', 'Float'), ('STR', 'String')], max_length=3),
        ),
        migrations.AlterField(
            model_name='listoutputdefinition',
            name='element_type',
            field=models.CharField(choices=[('BLN', 'Boolean'), ('INT', 'Integer'), ('FIL', 'File'), ('FLT', 'Float'), ('STR', 'String')], max_length=3),
        ),
    ]
