# Generated by Django 2.2.5 on 2019-11-11 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0004_auto_20191104_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanInput',
            fields=[
                ('input_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.Input')),
                ('value', models.BooleanField()),
            ],
            bases=('django_analysis.input',),
        ),
        migrations.CreateModel(
            name='BooleanInputDefinition',
            fields=[
                ('inputdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.InputDefinition')),
            ],
            bases=('django_analysis.inputdefinition',),
        ),
        migrations.CreateModel(
            name='FileInputDefinition',
            fields=[
                ('inputdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.InputDefinition')),
            ],
            bases=('django_analysis.inputdefinition',),
        ),
        migrations.RemoveField(
            model_name='inputdefinition',
            name='input_specification',
        ),
        migrations.AddField(
            model_name='inputdefinition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputspecification',
            name='input_definitions',
            field=models.ManyToManyField(to='django_analysis.InputDefinition'),
        ),
        migrations.AlterField(
            model_name='analysisversion',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_version_set', to='django_analysis.Analysis'),
        ),
        migrations.AlterField(
            model_name='analysisversion',
            name='input_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_version_set', to='django_analysis.InputSpecification'),
        ),
        migrations.AlterField(
            model_name='inputdefinition',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FileInput',
            fields=[
                ('input_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analysis.Input')),
                ('path', models.FilePathField(verbose_name='/home/zvi/Projects/pylabber/media')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_analysis.FileInputDefinition')),
            ],
            bases=('django_analysis.input',),
        ),
    ]
