# Generated by Django 3.0.6 on 2020-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0005_auto_20200716_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryinput',
            name='value',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=1000, verbose_name='/mnt/pylabber/media'),
        ),
        migrations.AlterField(
            model_name='fileoutput',
            name='value',
            field=models.FilePathField(blank=True, max_length=1000, null=True, verbose_name='/mnt/pylabber/media'),
        ),
    ]
