# Generated by Django 3.0.8 on 2020-09-29 02:40

from django.conf import settings
from django.db import migrations, models

MEDIA_ROOT = getattr(settings, "MEDIA_ROOT")


class Migration(migrations.Migration):

    dependencies = [
        ("django_analyses", "0005_auto_20200926_0855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryinput",
            name="value",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                max_length=1000,
                path=MEDIA_ROOT,
            ),
        ),
        migrations.AlterField(
            model_name="fileoutput",
            name="value",
            field=models.FilePathField(
                blank=True, max_length=1000, null=True, path=MEDIA_ROOT
            ),
        ),
    ]
