# Generated by Django 2.2.5 on 2019-11-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0006_auto_20191113_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileoutput',
            name='value',
            field=models.FilePathField(blank=True, null=True, verbose_name='/home/zvi/Projects/pylabber/media'),
        ),
    ]
