# Generated by Django 3.1.2 on 2020-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0007_auto_20201009_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisversion',
            name='fixed_run_method_kwargs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='listinput',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='listinputdefinition',
            name='default',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listoutput',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
    ]
