# Generated by Django 3.0.7 on 2020-08-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0007_auto_20200730_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryinput',
            name='value',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=1000, verbose_name='/media/groot/Data/media'),
        ),
        migrations.AlterField(
            model_name='fileoutput',
            name='value',
            field=models.FilePathField(blank=True, max_length=1000, null=True, verbose_name='/media/groot/Data/media'),
        ),
    ]
