# Generated by Django 2.2.5 on 2019-11-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0008_analysisversion_nested_results_attribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisversion',
            unique_together={('analysis', 'title')},
        ),
    ]
