# Generated by Django 3.0.7 on 2020-08-18 04:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0008_auto_20200801_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='TupleInputDefinition',
            fields=[
                ('inputdefinition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analyses.InputDefinition')),
                ('element_type', models.CharField(choices=[('BLN', 'Boolean'), ('INT', 'Integer'), ('FIL', 'File'), ('FLT', 'Float'), ('STR', 'String'), ('TUP', 'Tuple')], max_length=3)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('default', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('as_tuple', models.BooleanField(default=False)),
            ],
            bases=('django_analyses.inputdefinition',),
        ),
        migrations.CreateModel(
            name='TupleInput',
            fields=[
                ('input_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_analyses.Input')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_set', to='django_analyses.TupleInputDefinition')),
            ],
            bases=('django_analyses.input',),
        ),
    ]
