# Generated by Django 3.0.7 on 2020-09-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0009_tupleinput_tupleinputdefinition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tupleinputdefinition',
            name='as_tuple',
        ),
        migrations.AddField(
            model_name='pipe',
            name='group',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
