# Generated by Django 3.1.3 on 2021-01-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0009_auto_20201115_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(blank=True, choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
