# Generated by Django 3.1.3 on 2021-03-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0010_auto_20210101_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisversion',
            options={'ordering': ('analysis', '-title')},
        ),
        migrations.AlterField(
            model_name='analysisversion',
            name='fixed_run_method_kwargs',
            field=models.JSONField(default=dict, help_text='Fixed run method keyword arguments'),
        ),
        migrations.AlterField(
            model_name='analysisversion',
            name='max_parallel',
            field=models.PositiveIntegerField(default=4, help_text='Maximal number of parallel executions'),
        ),
        migrations.AlterField(
            model_name='analysisversion',
            name='nested_results_attribute',
            field=models.CharField(blank=True, help_text='Name of an attribute to be returned or called in order to retreive the output dictionary', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysisversion',
            name='run_method_key',
            field=models.CharField(default='run', help_text='Custom run method name', max_length=100),
        ),
        migrations.AlterField(
            model_name='inputdefinition',
            name='db_value_preprocessing',
            field=models.CharField(blank=True, help_text="Calls or returns the specified input value's attribute when saved to the database", max_length=255, null=True, verbose_name='DB Value Preprocessing'),
        ),
        migrations.AlterField(
            model_name='inputdefinition',
            name='is_configuration',
            field=models.BooleanField(default=True, help_text='Whether this definition represents a configuration of the analysis (rather than data input)'),
        ),
        migrations.AlterField(
            model_name='inputdefinition',
            name='run_method_input',
            field=models.BooleanField(default=False, help_text='Pass this input when calling the run method (and not at interface initialization)'),
        ),
        migrations.AlterField(
            model_name='inputdefinition',
            name='value_attribute',
            field=models.CharField(blank=True, help_text="Calls or returns the specified input value's attribute when passed to the interface", max_length=255, null=True),
        ),
    ]
