# Generated by Django 3.1.3 on 2021-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analyses', '0011_auto_20210318_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='destination_run_index',
            field=models.PositiveIntegerField(default=0, help_text='If the destination node is executed multiple times within the pipline, this attribute determines the index of the execution that will be used.'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='index',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="If the destination port is a list, use this index for the source port's output. If None, simply append to the list.", null=True),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='source_run_index',
            field=models.PositiveIntegerField(default=0, help_text='If the source node is executed multiple times within the pipline, this attribute determines the index of the execution that will be used.'),
        ),
    ]
