# Generated by Django 2.2.5 on 2019-11-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0011_auto_20191117_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputspecification',
            old_name='input_definitions',
            new_name='base_input_definitions',
        ),
        migrations.RenameField(
            model_name='outputspecification',
            old_name='output_definitions',
            new_name='base_output_definitions',
        ),
    ]
