# Generated by Django 3.2.6 on 2021-11-23 13:29

import django_analyses.models.utils.json_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_analyses", "0012_auto_20210420_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisversion",
            name="fixed_run_method_kwargs",
            field=django_analyses.models.utils.json_field.DefaultJSONField(
                blank=True,
                default=dict,
                help_text="Fixed run method keyword arguments",
            ),
        ),
    ]
