# Generated by Django 2.2.5 on 2019-11-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0012_auto_20191118_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringinputdefinition',
            name='is_output_path',
            field=models.BooleanField(default=False),
        ),
    ]
