# Generated by Django 2.2.5 on 2019-11-18 09:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0013_stringinputdefinition_is_output_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinputdefinition',
            name='default',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
