# Generated by Django 2.2.5 on 2019-11-21 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_analysis', '0014_listinputdefinition_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ('title',), 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='analysisversion',
            options={'ordering': ('-title',)},
        ),
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
