# Generated by Django 2.2.5 on 2019-11-26 04:11

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0017_auto_20191125_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputdefinition',
            options={'ordering': ('key',)},
        ),
        migrations.AlterModelOptions(
            name='outputspecification',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='outputspecification',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputspecification',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
