# Generated by Django 2.2.5 on 2019-11-26 09:32

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0018_auto_20191126_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='node',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
