# Generated by Django 2.2.5 on 2019-11-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_analysis', '0019_auto_20191126_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipe',
            old_name='destination_port',
            new_name='base_destination_port',
        ),
        migrations.RenameField(
            model_name='pipe',
            old_name='source_port',
            new_name='base_source_port',
        ),
    ]
